### ISSUE TITLE
what uses this module?

### ISSUE THREAD

**Issue by ktdreyer** [release-engineering/fedmsg_meta_umb#24]
Could you provide a bit more context about what code or applications might use this module? Is it just for datagrepper, or do you envision it for more broad use-cases?

For example, I'm currently working on a project that will consume UMB messages and print a one-line summary of each of them (to IRC in my case). Would this library be ok to use for that?

**Comment by ralphbean** [comment]
> do you envision it for more broad use-cases?

Yes.

> For example, I'm currently working on a project that will consume UMB messages and print a one-line summary of each of them (to IRC in my case). Would this library be ok to use for that?

Yes, that's perfect.  :)

Note, the best API to *use* from an app (say, your irc bot) is `fedmsg.meta.msg2subject(msg, **config)` and `fedmsg.meta.msg2link(msg, **config)` (for instance) to get the values out.
